
language: c
sudo: false

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/docker/pkg-build.sh
  - chmod 755 pkg-build.sh
  - cp pkg-build.sh rbuildertest
  - cd rbuildertest
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_build
  - ./pkg-build.sh run_check

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
 
addons:
  apt:
    packages:
    - pandoc
    - gfortran
    - texlive-base
    - texlive-latex-base
    - texlive-generic-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-extra-utils
    - texlive-latex-recommended
    - texlive-latex-extra
    - texinfo
